### ISSUE TITLE
Bug: Autoscroll button toggles unwanted.

### ISSUE THREAD

**Issue by elli-one** [CobaltFusion/DebugViewPP#305] opened 2017-09-29 19:54 UTC
When the last action was pressing the auto scroll button and than the mouse is moved to the trace view
window and clicked to select a line than the auto scroll button state is changed.

**Comment by janwilmans** [comment] 2017-09-30 23:44
Hi, yes this is the defined behaviour when 'Stop scroll stop' is enabled. If you dont like the behaviour, yes disabled it. (this is a persistent setting)

![image](https://user-images.githubusercontent.com/5933444/31050416-840ea9f4-a5fe-11e7-852f-ba951be0c125.png)

**Comment by janwilmans** [comment] 2017-10-02 07:29
closing this issue as 'by design'

**Closed by janwilmans** 2017-10-02 07:29 UTC
Labels: question
