### ISSUE TITLE
copy  Chinese text from  view  got garbled string

### ISSUE THREAD

**Issue by raidsan** [CobaltFusion/DebugViewPP#328] opened 2018-07-29 13:46 UTC
change font not help

**Comment by janwilmans** [comment] 2018-07-29 18:14
Thanks for reporting, I have no idea how to debug this, I cannot read Chinese, could you provide a saved logfile and the expected outcome?

**Comment by raidsan** [comment] 2018-07-31 20:25
just use c#  Trace.WriteLine("some 中文"), 
in the view ,  It looks ok,  export  log to file  is also ok,  but  copy to clipboard will became garbled

**Comment by raidsan** [comment] 2018-07-31 20:29
![snipaste_2018-08-01_04-27-06](https://user-images.githubusercontent.com/877029/43485254-45270ec2-9543-11e8-992e-8224ce4e55da.png)
same garbled in  statusbar:  searching: ...

**Comment by janwilmans** [comment] 2018-07-31 22:44
thanks ! I have tried to reproduce, but it seem to behave diffenent:
![image](https://user-images.githubusercontent.com/5933444/43491229-39ac6c16-9513-11e8-927e-b14be788a636.png)

**Comment by janwilmans** [comment] 2018-08-17 07:25
Wow, nice work, I'll process this!

**Comment by janwilmans** [comment] 2018-08-18 14:58
you propose to change the use of MultiByteToWideChar  to std:: mbstowcs, and to copy data to the clipboard using the CF_UNICODETEXT flag, both changes sound good. However, I still cannot reproduce the issue. 

If you run this program, do the characters show up in debugview++ ? (I see this:

![image](https://user-images.githubusercontent.com/5933444/44300484-e19c1000-a307-11e8-888f-00a050e5c730.png)

Test program:
[showchinesechars.zip](https://github.com/CobaltFusion/DebugViewPP/files/2299620/showchinesechars.zip)

**Comment by janwilmans** [comment] 2018-08-18 19:27
I'm trying very hard to make sense of this, in your example, you used

```std::mbstowcs``` preceeded by ```setlocale(LC_ALL, ""); ```

This does not make sense to me, I think std::mbstowcs is not affected by setlocale, I think it should be 
```std::setlocale``` from ```<clocale> ```

**Comment by janwilmans** [comment] 2018-08-18 23:47
Please try how this works:
https://github.com/CobaltFusion/DebugViewPP/releases/tag/v1.8.0.21

I have tried to simulate the conversions in a test, but I still don't actually 'see' the behavior in debugview++ :) You did uncover a real problem in 
```
basic_stringbuilder& operator<<(const std::wstring& str)
```
It was very much broken and could crash (now fixed)

**Comment by janwilmans** [comment] 2018-08-19 09:41
I tried to set my windows locale to Chinese, aside from being really difficult to understand my system dialogs, it did not seem to effect debugview 

![image](https://user-images.githubusercontent.com/5933444/44307579-cdf2b700-a3a4-11e8-9a4f-87753250e672.png)

I'm still getting ?? and ???? instead of proper characters.

**Comment by raidsan** [comment] 2018-08-19 09:58
make sure set windows locale to  chinese,   for windows 10 english version:     Setting:  =>"Time & Language” => "Region & language – Additional date, time & regional settings”=>"Change date, time or number formats" => "Administrative - Change system locale…",  choose:  “Chinese（Simplified, China）",   restart

**Comment by janwilmans** [comment] 2018-08-19 11:26
Did the new version I put up work any better?

**Comment by raidsan** [comment] 2018-08-19 12:04
I just test  v1.8.0.21 - version,   it act same as  the old version

**Comment by janwilmans** [comment] 2018-08-19 13:03
That is very sad, it spend several hours on that :)

On the bright side:
Changing this, as you suggested, worked:

![image](https://user-images.githubusercontent.com/5933444/44309071-06a08980-a3c1-11e8-96ad-54ec3a66f663.png)

![image](https://user-images.githubusercontent.com/5933444/44309063-e96bbb00-a3c0-11e8-852a-fc2b54a3b424.png)

**Comment by janwilmans** [comment] 2018-08-20 14:05
reopened, to get confirmation that is it actually working correctly now.

**Comment by raidsan** [comment] 2018-08-20 14:34
yes,  I test it copy text ok,  except select and highlight text length

**Comment by raidsan** [comment] 2018-08-20 14:37
but status text show:  searching : ....   is still  garbled

**Closed** 2018-08-21 20:49 UTC
Labels: bug
